import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
    'hi_IN': {
      //menu
      'edit_profile': 'प्रोफ़ाइल एडिट करें',
      'change_password': 'पासवर्ड बदलें',
      'change_language': 'भाषा बदलें',
      'how_to_use': 'उपयोग कैसे करें',
      'demo_video': 'डेमो वीडियो',
      'about_us': 'हमारे बारे में',
      'hello': 'नमस्ते', //hindi
      'message': "एक सेंसर चुनें",
      'message_gas': "एक गैस चुनें",
      'title': 'सेंसर ऐप',
      'water': 'जल',
      'gas': 'हवा',
      'soil': 'मिट्टी',
      'bio': 'जैव',
      //agriculture
      'agriculture': 'कृषि',
      'disease_detector': 'रोग डिटेक्टर',
      'npk_sensor': 'NPK सेंसर ',
      'agri_subtitle':
      'रोग के बारे में सुनिश्चित करने के लिए रोग डिटेक्टर और एनपीके सेंसर दोनों का उपयोग करके अपनी फसल में रोग का पता लगाएं',
      //disease detector
      'disease_detector': 'रोग डिटेक्टर',
      'crop': 'फसल',
      'select_type': 'फसल का प्रकार चुनें',
      'choose_kharif': 'एक खरीफ फसल चुनें',
      'choose_rabi': 'एक रबी फसल चुनें',
      'kharif': 'ख़रीफ़',
      'rabi': 'रबी',
      'select_crop': 'फसल का चयन करें',
      'add_image': 'छवि जोड़ें',
      'potato': 'आलू',
      'soyabean': 'सोयाबीन',
      'maize': 'मक्का',
      'rice': 'चावल',
      'gram': 'चना',
      'wheat': 'गेहूँ',
      'proceed': 'आगे बढ़ें',
      'disease_det_subtitle':
      'एक फसल चुनें और एक पत्ती की छवि अपलोड करें। ऐप एमएल मॉडल से बीमारी की भविष्यवाणी करेगा और उपचार सुझाएगा।',
      'gallery': 'गैलरी',
      'camera': 'कैमरा',
      //results
      'prediction': 'पूर्वानुमान',
      'suggestions': 'सुझाव',
      'reasons': 'कारण',
      'measures': 'उपाय',
      'commercial_solutions': 'व्यावसायिक समाधान',
      'home_remedies': 'घरेलू उपचार',
      // npk sensor
      'npk_sensor': 'NPK सेंसर',
      'npk_subtitle':
      'NPK सेंसर का उपयोग मिट्टी में नाइट्रोजन, फॉस्फोरस और पोटैशियम की मात्रा का पता लगाने के लिए किया जाता है।',
      'select_soil_type': 'मिट्टी का प्रकार चुनें',
      'has_crop': 'क्या आपके खेत में फसल है?',
      'add_img': 'या यह प्रकार का पता लगाने के लिए मिट्टी की छवि जोड़ें',
      'yes': 'हाँ',
      'no': 'नहीं',
      'red_soil': 'लाल मिट्टी',
      'black_soil': 'काली मिट्टी',
      'alluvial_soil': 'जलोढ़ मिट्टी',
      'tick_box':
      'कृपया सुनिश्चित करें कि आपका सेंसर ESP32 चालू है और ठीक से काम कर रहा है।',
      //History
      'history': 'इतिहास',
      'reading_history': 'NPK रीडिंग हिस्ट्री',
      'no_data': "कोई पढ़ना उपलब्ध नहीं है",
      // NPK ANALYSER
      'current_reading': 'वर्तमान पढ़ना: ',
      'analyzer_heading':'NPK विश्लेषक ',
      'Nitrogen': 'नाइट्रोजन',
      //gases
      'CO2': 'कार्बन डाइआक्साइड',
      'SO2': 'सल्फर डाइऑक्साइड',
      'NO2': 'नाइट्रोजन डाइऑक्साइड',
      'Concentration': 'एकाग्रता',
      'Pure': 'शुद्ध',
      "Good": 'ठीक',
      "Moderate": "मध्यम",
      "Unhealthy": "अस्वस्थ",
      "Hazardous": "खतरनाक",
      "Update": "अपडेट करें",
      "Change Language": "भाषा बदलें",
      "Warning": "चेतावनी",
      "Okay": "ठीक है",
      "Warning_msg": "एकाग्रता खतरनाक सीमा में है",
      "Logout": "लॉग आउट",
      "How to Use?": "उपयोग कैसे करें?",
    },
    'en_US': {
      //menu
      'edit_profile': 'Edit profile',
      'change_password': 'Change password',
      'change_language': 'Change language',
      'how_to_use': 'How to use',
      'demo_video': 'Demo video',
      'about_us': 'About us',
      'hello': 'Welcome',
      //englishwater
      'message': "Choose a sensor",
      'message_gas': "Choose a gas",
      "title": "Sensor App",
      'water': 'Water',
      'gas': 'Gas',
      'soil': 'Soil',
      'bio': 'Bio',
      //agriculture
      'agriculture': 'Agriculture',
      'agri_subtitle':
      'Detect disease in your crop using both Disease Detector and NPK sensor to be sure about the disease.',
      'disease_detector': 'Disease Detector',
      'npk_sensor': 'NPK Sensor',
      'agri_subtitle':
      'Detect disease in your crop using both disease detector and NPK senssor to be sure about the disease.',
      //disease detector
      'disease_detector': 'Disease Detector',
      'crop': 'Crop',
      'select_type': 'Select crop type',
      'choose_kharif': 'Choose a kharif crop',
      'choose_rabi': 'Choose a rabi crop',
      'kharif': 'Kharif',
      'rabi': 'Rabi',
      'select_crop': 'Select crop',
      'add_image': 'Add Image',
      'potato': 'Potato',
      'soyabean': 'Soyabean',
      'maize': 'Maize',
      'rice': 'Rice',
      'gram': 'Gram',
      'wheat': 'Wheat',
      'proceed': 'Proceed',
      'disease_det_subtitle':
      'Select a crop and upload a leaf image. The app will predict the disease with ML Model and suggest remedies.',
      'gallery': 'Gallery',
      'camera': 'Camera',
      //results
      'prediction': 'Prediction',
      'suggestions': 'Suggestions',
      'reasons': 'Reasons',
      'measures': 'Measures',
      'commercial_solutions': 'Commercial Solutions',
      'home_remedies': 'Home Remedies',
      // npk sensor
      'npk_sensor': 'NPK Sensor',
      'npk_subtitle':
      'NPK sensor is used to detect the amount of nitrogen, phosphorus and potassium in the soil.',
      'select_soil_type': 'Select Soil Type',
      'has_crop': 'Does your field has crop ?',
      'add_img': 'or add soil image to detect its type',
      'yes': "Yes",
      'no': 'No',
      'red_soil': 'Red Soil',
      'black_soil': 'Black Soil',
      'alluvial_soil': 'Alluvial Soil',
      'tick_box':
      'Please make sure your sensor ESP32 is switched on and working properly.',
      //History
      'history': 'History',
      'reading_history': 'NPK Readings History',
      'no_data': "No readings Available",
      // NPK ANALYSER
      'current_reading': 'Current Reading',
      'analyzer_heading':'NPK Analyzer',
      //gases
      'CO2': 'Carbon Dioxide',
      'SO2': 'Sulphur Dioxide',
      'NO2': 'Nitrogen Dioxide',
      'Concentration': 'Concentration',
      'Pure': 'Pure',
      "Good": 'Good',
      "Moderate": "Moderate",
      "Unhealthy": "Unhealthy",
      "Hazardous": "Hazardous",
      "Update": "Update",
      "Change Language": "Change Language",
      "Warning": "Warning",
      "Okay": "Okay",
      "Warning_msg": "The concentration is in Hazardous range",
      "Logout": "Logout",
      "How to Use?": "How to Use?",
    },
    'kan_KAR': {
      //menu
      'edit_profile': 'ಪ್ರೊಫೈಲ್ ಬದಲಿಸು',
      'change_password': 'ಗುಪ್ತಪದವನ್ನು ಬದಲಿಸಿ',
      'change_language': 'ಭಾಷೆ ಬದಲಾಯಿಸಿ',
      'how_to_use': 'ಬಳಸುವುದು ಹೇಗೆ',
      'demo_video': 'ಡೆಮೊ ವಿಡಿಯೋ',
      'about_us': 'ನಮ್ಮ ಬಗ್ಗೆ',
      'hello': 'ಸ್ವಾಗತ',
      //englishwater

      'message': "ಸಂವೇದಕವನ್ನು ಆರಿಸಿ",
      'message_gas': "ಅನಿಲವನ್ನು ಆರಿಸಿ",
      "title": "ಸಂವೇದಕ ಅಪ್ಲಿಕೇಶನ್",
      'water': 'ನೀರು',
      'gas': 'ಅನಿಲ',
      'soil': 'ಮಣ್ಣು',
      'bio': 'ಜೈವಿಕ',
      //agriculture
      'agriculture': 'ಕೃಷಿ',
      'disease_detector': 'ರೋಗ ಪತ್ತೆಕಾರಕ',
      'npk_sensor': 'NPK ಸಂವೇದಕ',
      'agri_subtitle':
      'ರೋಗದ ಬಗ್ಗೆ ಖಚಿತವಾಗಿರಲು ರೋಗ ಪತ್ತೆಕಾರಕ ಮತ್ತು NPK ಸಂವೇದಕ ಎರಡನ್ನೂ ಬಳಸಿಕೊಂಡು ನಿಮ್ಮ ಬೆಳೆಯಲ್ಲಿ ರೋಗವನ್ನು ಪತ್ತೆ ಮಾಡಿ',
      //disease detector
      'disease_detector': 'ರೋಗ ಪತ್ತೆಕಾರಕ',
      'crop': 'ಬೆಳೆ',
      'select_type': 'ಬೆಳೆ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'choose_kharif': 'ಒಂದು ಖರೀಫ್ ಬೆಳೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'choose_rabi': 'ಒಂದು ರಬಿ ಬೆಳೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'kharif': 'ಖಾರಿಫ್',
      'rabi': 'ರಬಿ',
      'select_crop': 'ಬೆಳೆ ಆಯ್ಕೆ ಮಾಡಿ',
      'add_image': 'ಚಿತ್ರವನ್ನು ಸೇರಿಸಿ',
      'potato': 'ಆಲೂಗಡ್ಡೆ',
      'soyabean': 'ಸೋಯಾಬೀನ್',
      'maize': 'ಮೆಕ್ಕೆಜೋಳ',
      'rice': 'ಅಕ್ಕಿ',
      'wheat': 'ಗೋಧಿ',
      'gram': 'ಗ್ರಾಂ',
      'proceed': 'ಮುಂದುವರೆಯಲು',
      'disease_det_subtitle':
      'ಕ್ರಾಪ್ ಆಯ್ಕೆಮಾಡಿ ಮತ್ತು ಎಲೆಯ ಚಿತ್ರವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ. ಅಪ್ಲಿಕೇಶನ್ ML ಮಾದರಿಯೊಂದಿಗೆ ರೋಗವನ್ನು ಊಹಿಸುತ್ತದೆ ಮತ್ತು ಪರಿಹಾರಗಳನ್ನು ಸೂಚಿಸುತ್ತದೆ.',
      'gallery': 'ಗ್ಯಾಲರಿ',
      'camera': 'ಕ್ಯಾಮರಾ',
      //results
      'prediction': 'ಮುನ್ಸೂಚನೆ',
      'suggestions': 'ಸಲಹೆಗಳು',
      'reasons': 'ಕಾರಣಗಳು',
      'measures': 'ಕ್ರಮಗಳು',
      'commercial_solutions': 'ವಾಣಿಜ್ಯ ಪರಿಹಾರಗಳು',
      'home_remedies': 'ಮನೆಮದ್ದುಗಳು',
      // npk sensor
      'npk_sensor': 'NPK ಸಂವೇದಕ',
      'npk_subtitle':
      'NPK ಸೆನ್ಸರ್ ಮಣ್ಣಿನಲ್ಲಿ ನೈಟ್ರೊಜನ್, ಫಾಸ್ಫರಸ್ ಮತ್ತು ಪೊಟಾಶಿಯಂ ಅಳತೆಯನ್ನು ಕಂಡುಹಿಡಿಯಲು ಬಳಸಲಾಗುತ್ತದೆ.',
      'select_soil_type': 'ಮಣ್ಣಿನ ಪ್ರಕಾರವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'has_crop': 'ನಿಮ್ಮ ಹೊಲದಲ್ಲಿ ಬೆಳೆ ಇದೆಯೇ?',
      'add_img':
      'ಅಥವಾ ಅದರ ಪ್ರಕಾರವನ್ನು ಕಂಡುಹಿಡಿಯಲು ಮಣ್ಣಿನ ಚಿತ್ರವನ್ನು ಸೇರಿಸಿ',
      'yes': 'ಹೌದು',
      'no': 'ಇಲ್ಲ',
      'red_soil': 'ಕೆಂಪು ಮಣ್ಣು',
      'black_soil': 'ಕಪ್ಪು ಮಣ್ಣು',
      'alluvial_soil': 'ಮೆಕ್ಕಲು ಮಣ್ಣು',
      'tick_box':
      'ದಯವಿಟ್ಟು ನಿಮ್ಮ ಸಂವೇದಕ ಇಎಸ್ಪಿ 32 ಅನ್ನು ಸ್ವಿಚ್ ಆನ್ ಮಾಡಲಾಗಿದೆ ಮತ್ತು ಸರಿಯಾಗಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತಿದೆ ಎಂದು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ.',
      //History
      'history': 'ಇತಿಹಾಸ',
      'reading_history': 'NPK ವಾಚನಗೋಷ್ಠಿಗಳು ಇತಿಹಾಸ',
      'no_data': "ಯಾವುದೇ ಓದುವಿಕೆ ಲಭ್ಯವಿಲ್ಲ",
      //gases
      'CO2': 'ಇಂಗಾಲದ ಡೈಆಕ್ಸೈಡ್',
      'SO2': 'ಸಲ್ಫರ್ ಡೈಆಕ್ಸೈಡ್',
      'NO2': 'ಸಾರಜನಕ ಡೈಆಕ್ಸೈಡ್',
      'Concentration': 'ಏಕಾಗ್ರತೆ',
      'Pure': 'ಶುದ್ಧ',
      "Good": 'ಒಳ್ಳೆಯದು',
      "Moderate": "ಮಧ್ಯಮ",
      "Unhealthy": "ಅನಾರೋಗ್ಯಕರ",
      "Hazardous": "ಅಪಾಯಕಾರಿ",
      "Update": "ನವೀಕರಿಸಿ",
      "Change Language": "ಭಾಷೆ ಬದಲಾಯಿಸಿ",
      "Warning": "ಎಚ್ಚರಿಕೆ",
      "Okay": "ಸರಿ",
      "Warning_msg": "ಸಾಂದ್ರತೆಯು ಅಪಾಯಕಾರಿ ವ್ಯಾಪ್ತಿಯಲ್ಲಿದೆ",
      "Logout": "ಲಾಗ್ ಔಟ್",
      "How to Use?": "ಬಳಸುವುದು ಹೇಗೆ?",
    },
    'tam_TN': {
      //menu
      'edit_profile': 'சுயவிவரத்தைத் திருத்தவும்',
      'change_password': 'கடவுச்சொல்லை மாற்று',
      'change_language': 'மொழியை மாற்றவும்',
      'how_to_use': 'எப்படி உபயோகிப்பது',
      'demo_video': 'டெமோ வீடியோ',
      'about_us': 'எங்களை பற்றி',
      'hello': 'வரவேற்பு', //englishwater

      'message': "ஒரு சென்சார் தேர்வு செய்யவும்",
      'message_gas': "ஒரு வாயுவைத் தேர்ந்தெடுக்கவும்",
      "title": "சென்சார் பயன்பாடு",
      'water': 'தண்ணீர்',
      'gas': 'வாயு',
      'soil': 'வேளாண்மை',
      'bio': 'உயிர்',
      //agriculture
      'agriculture': 'வேளாண்மை',
      'disease_detector': 'நோய் கண்டறிதல்',
      'npk_sensor': 'NPK சென்சார்',
      'agri_subtitle':
      'நோயைக் கண்டறியும் கருவி மற்றும் NPK சென்சார் இரண்டையும் பயன்படுத்தி உங்கள் பயிரில் நோயைக் கண்டறியவும்',
      //disease detector
      'disease_detector': 'நோய் கண்டறிதல்',
      'crop': 'பயிர்',
      'select_type': 'பயிர் வகையைத் தேர்ந்தெடுக்கவும்',
      'choose_kharif': 'ஒரு காரீஃப் பயிரைத் தேர்ந்தெடுக்கவும்',
      'choose_rabi': 'ஒரு ரபி பயிரைத் தேர்ந்தெடுக்கவும்',
      'kharif': 'காரீஃப்',
      'rabi': 'ரபி',
      'select_crop': 'பயிர் தேர்ந்தெடுக்கவும்',
      'add_image': 'படத்தைச் சேர்க்கவும்',
      'potato': 'உருளைக்கிழங்கு',
      'soyabean': 'சோயாபீன்',
      'maize': 'சோளம்',
      'rice': 'ಅಕ್ಕಿ',
      'wheat': 'கோதுமை',
      'gram': 'கிராம்',
      'proceed': 'தொடர',
      'disease_det_subtitle':
      'ஒரு செதுக்கியைத் தேர்ந்தெடுத்து, இலைப் படத்தைப் பதிவேற்றவும். பயன்பாடு ML மாதிரியுடன் நோயைக் கணித்து, தீர்வுகளை பரிந்துரைக்கும்.',
      'gallery': 'கேலரி',
      'camera': 'கேமரா',
      //results
      'prediction': 'கணிப்பு',
      'suggestions': 'பரிந்துரைகள்',
      'reasons': 'காரணங்கள்',
      'measures': 'நடவடிக்கைகள்',
      'commercial_solutions': 'வணிக தீர்வுகள்',
      'home_remedies': 'வீட்டு வைத்தியம்',
      // npk sensor
      'npk_sensor': 'NPK சென்சார்',
      'npk_subtitle':
      'NPK சென்சார் மண்ணில் நைட்ரஜன், பாஸ்போரஸ் மற்றும் போட்டாஷியம் அளவைக் கண்டுபிடிக்க பயன்படுகிறது.',
      'select_soil_type': 'மண் வகையைத் தேர்ந்தெடுக்கவும்',
      'has_crop': 'உங்கள் வயலில் பயிர் இருக்கிறதா?',
      'add_img': 'அல்லது அதன் வகையைக் கண்டறிய மண் படத்தைச் சேர்க்கவும்',
      'yes': 'ஆம்',
      'no': 'இல்லை',
      'red_soil': 'சிவப்பு மண்',
      'black_soil': 'கருப்பு மண்',
      'alluvial_soil': 'வண்டல் மண்',
      'tick_box':
      'உங்கள் சென்சார் ESP32 இயக்கப்பட்டு சரியாக வேலை செய்வதை உறுதிப்படுத்தவும்.',
      //History
      'history': 'வரலாறு',
      'reading_history': 'NPK வாசிப்புகள் வரலாறு',
      'no_data': "வாசிப்பு எதுவும் கிடைக்கவில்லை",
      //gases
      'CO2': 'கார்பன் டை ஆக்சைடு',
      'SO2': 'சல்பர் டை ஆக்சைடு',
      'NO2': 'நைட்ரஜன் டை ஆக்சைடு',
      'Concentration': 'செறிவு',
      'Pure': 'தூய்மையான',
      "Good": 'நல்ல',
      "Moderate": "மிதமான",
      "Unhealthy": "ஆரோக்கியமற்ற",
      "Hazardous": "ஆரோக்கியமற்ற",
      "Update": "மேம்படுத்தல்",
      "Change Language": "மொழியை மாற்றவும்",
      "Warning": "எச்சரிக்கை",
      "Okay": "சரி",
      "Warning_msg": "செறிவு அபாயகரமான வரம்பில் உள்ளது",
      "Logout": "வெளியேறு",
      "How to Use?": "எப்படி உபயோகிப்பது?",
    },
  };
}
