on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - dev
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
      - run: flutter pub get
      - run: flutter build apk